export const DAYS = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday"
];

export const BRGYS = [
    "Altura",
    "Bata",
    "Matanda",
    "South",
    "Ambulong",
    "Bagbag",
    "Bagumbayan",
    "Balele",
    "Bañadero",
    "Banjo East",
    "Banjo Laurel",
    "Bilog-Bilog",
    "Boot",
    "Cale",
    "Darasa",
    "Gonzales",
    "Hidalgo",
    "Janopol Occidental",
    "Janopol Oriental",
    "Laurel",
    "Luyos",
    "Mabini",
    "Malaking Pulo",
    "Maria Paz",
    "Montana",
    "Natatas",
    "Pantay Bata",
    "Pantay Matanda",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Poblacion 5",
    "Poblacion 6",
    "Poblacion 7",
    "Sala",
    "Sambat",
    "Santor",
    "Sulpang",
    "Suplang",
    "Talaga",
    "Tinurik",
    "Ulango",
    "Wawa",
    "Quiling",
    "Aya",
    "Rizal St.",
    "Tranca",
    "Banga",
    "Luta Norte",
]